### ISSUE TITLE
Fast

### ISSUE THREAD

**Issue by iagooar** [haileys/fast_open_struct#5]
I don't want to be a troll, but why is the gem called fast_open_struct, if it is only faster if a given set of conditions is met and otherwise it is significantly slower? 

How am I supposed to use it as a drop in replacement when it's likely going to perform slower in some scenarios? Or maybe I am wrong and this is only an experiment?

**Comment by haileys** [comment]
The main reason I call it 'fast' open struct is because it respects MRI's method caches. So the rest of your app stays fast, even if fast_open_struct is actually slower.
